// @vitest-environment node
import { afterEach, beforeEach, describe, expect, it, vi } from "vitest";

vi.mock("@/lib/recording-kit", () => ({
  preflightVoiceProfileRecordingKit: vi.fn(),
}));

import { POST } from "@/app/api/voice-profile/recording-kit/preflight/route";
import { preflightVoiceProfileRecordingKit } from "@/lib/recording-kit";
import { ANYVOICE_USER_COOKIE } from "@/lib/user-session";

const preflightKitMock = vi.mocked(preflightVoiceProfileRecordingKit);
const originalEnv = { ...process.env };

function makeReq(body?: unknown): import("next/server").NextRequest {
  return new Request("http://localhost/api/voice-profile/recording-kit/preflight", {
    method: "POST",
    headers: body === undefined ? undefined : { "content-type": "application/json" },
    body: body === undefined ? undefined : JSON.stringify(body),
  }) as unknown as import("next/server").NextRequest;
}

beforeEach(() => {
  vi.clearAllMocks();
  preflightKitMock.mockResolvedValue({
    status: "ready_to_record",
    manifest: "/tmp/anyvoice-kit/manifest.json",
    message: "5 clip(s) will be recorded",
    durationSec: 9,
    countdownSec: 0,
    summary: {
      clips: 5,
      existing: 0,
      toRecord: 5,
      toSkipExisting: 0,
      promptBlocked: 0,
      transcriptBlocked: 0,
      recordingMetadataChecked: 0,
      recordingMetadataBlocked: 0,
      writeBlocked: 0,
    },
    recorder: {
      configured: true,
      source: "sox:rec",
      template: "rec {audio_path}",
    },
  });
});

afterEach(() => {
  for (const key of Object.keys(process.env)) {
    if (!(key in originalEnv)) delete process.env[key];
  }
  Object.assign(process.env, originalEnv);
});

describe("POST /api/voice-profile/recording-kit/preflight", () => {
  it("runs a no-microphone recording-kit preflight and returns the report", async () => {
    const res = await POST(makeReq({ profileId: "local-default", manifest: "/tmp/anyvoice-kit/manifest.json" }));
    expect(res.status).toBe(200);
    expect(res.headers.get("set-cookie")).toContain(`${ANYVOICE_USER_COOKIE}=`);
    expect(preflightKitMock).toHaveBeenCalledWith("/tmp/anyvoice-kit/manifest.json", "local-default");
    const body = await res.json();
    expect(body.preflight).toMatchObject({
      status: "ready_to_record",
      summary: { toRecord: 5 },
      recorder: { source: "sox:rec" },
    });
  });

  it("uses a default profile id when no JSON body is sent", async () => {
    await POST(makeReq());
    expect(preflightKitMock).toHaveBeenCalledWith("", "local-default");
  });

  it("returns an error payload when the preflight cannot run", async () => {
    preflightKitMock.mockRejectedValue(new Error("manifest must be a recording kit manifest generated by AnyVoice"));
    const res = await POST(makeReq({ manifest: "/etc/passwd" }));
    expect(res.status).toBe(500);
    const body = await res.json();
    expect(body).toMatchObject({
      status: "error",
      message: "manifest must be a recording kit manifest generated by AnyVoice",
    });
  });
});
