// @vitest-environment node
import { afterEach, beforeEach, describe, expect, it, vi } from "vitest";

vi.mock("@/lib/recording-kit", () => ({
  smokeTestVoiceProfileRecordingKit: vi.fn(),
}));

import { POST } from "@/app/api/voice-profile/recording-kit/microphone-smoke-test/route";
import { smokeTestVoiceProfileRecordingKit } from "@/lib/recording-kit";
import { ANYVOICE_USER_COOKIE } from "@/lib/user-session";

const smokeTestKitMock = vi.mocked(smokeTestVoiceProfileRecordingKit);
const originalEnv = { ...process.env };

function makeReq(body?: unknown): import("next/server").NextRequest {
  return new Request("http://localhost/api/voice-profile/recording-kit/microphone-smoke-test", {
    method: "POST",
    headers: body === undefined ? undefined : { "content-type": "application/json" },
    body: body === undefined ? undefined : JSON.stringify(body),
  }) as unknown as import("next/server").NextRequest;
}

beforeEach(() => {
  vi.clearAllMocks();
  smokeTestKitMock.mockResolvedValue({
    status: "ready_to_record",
    manifest: "/tmp/anyvoice-kit/manifest.json",
    message: "5 clip(s) will be recorded",
    durationSec: 9,
    countdownSec: 0,
    summary: {
      clips: 5,
      existing: 0,
      toRecord: 5,
      toSkipExisting: 0,
      promptBlocked: 0,
      transcriptBlocked: 0,
      recordingMetadataChecked: 0,
      recordingMetadataBlocked: 0,
      writeBlocked: 0,
    },
    recorder: {
      configured: true,
      source: "sox:rec",
      template: "rec {audio_path}",
    },
    microphoneSmokeTest: {
      status: "passed",
      durationSec: 2,
      clipId: "profile-clip-01",
      exitCode: 0,
      audioBytes: 32044,
      keptAudio: false,
    },
  });
});

afterEach(() => {
  for (const key of Object.keys(process.env)) {
    if (!(key in originalEnv)) delete process.env[key];
  }
  Object.assign(process.env, originalEnv);
});

describe("POST /api/voice-profile/recording-kit/microphone-smoke-test", () => {
  it("runs the explicit microphone smoke test and returns the preflight report", async () => {
    const res = await POST(makeReq({ profileId: "local-default", manifest: "/tmp/anyvoice-kit/manifest.json" }));
    expect(res.status).toBe(200);
    expect(res.headers.get("set-cookie")).toContain(`${ANYVOICE_USER_COOKIE}=`);
    expect(smokeTestKitMock).toHaveBeenCalledWith("/tmp/anyvoice-kit/manifest.json", "local-default");
    const body = await res.json();
    expect(body.preflight).toMatchObject({
      status: "ready_to_record",
      microphoneSmokeTest: {
        status: "passed",
        audioBytes: 32044,
      },
    });
  });

  it("uses a default profile id when no JSON body is sent", async () => {
    await POST(makeReq());
    expect(smokeTestKitMock).toHaveBeenCalledWith("", "local-default");
  });

  it("returns an error payload when the smoke test cannot start", async () => {
    smokeTestKitMock.mockRejectedValue(new Error("manifest must be a recording kit manifest generated by AnyVoice"));
    const res = await POST(makeReq({ manifest: "/etc/passwd" }));
    expect(res.status).toBe(500);
    const body = await res.json();
    expect(body).toMatchObject({
      status: "error",
      message: "manifest must be a recording kit manifest generated by AnyVoice",
    });
  });
});
