// @vitest-environment node
import { afterEach, beforeEach, describe, expect, it, vi } from "vitest";

vi.mock("@/lib/voice-profile-access", () => ({
  guardVoiceProfileAccess: vi.fn(async () => null),
}));

vi.mock("@/lib/recording-kit", () => ({
  checkVoiceProfileRecordingKit: vi.fn(),
}));

import { POST } from "@/app/api/voice-profile/recording-kit/check/route";
import { checkVoiceProfileRecordingKit } from "@/lib/recording-kit";
import { ANYVOICE_USER_COOKIE } from "@/lib/user-session";

const checkKitMock = vi.mocked(checkVoiceProfileRecordingKit);
const originalEnv = { ...process.env };

function makeReq(body?: unknown): import("next/server").NextRequest {
  return new Request("http://localhost/api/voice-profile/recording-kit/check", {
    method: "POST",
    headers: body === undefined ? undefined : { "content-type": "application/json" },
    body: body === undefined ? undefined : JSON.stringify(body),
  }) as unknown as import("next/server").NextRequest;
}

beforeEach(() => {
  vi.clearAllMocks();
  checkKitMock.mockResolvedValue({
    status: "incomplete",
    manifest: "/tmp/anyvoice-kit/manifest.json",
    profileId: "local-default",
    summary: {
      clips: 5,
      minClips: 5,
      audioFilesPresent: 3,
      coveredFeatures: ["zh_hant"],
      missingCoverageFeatures: ["numbers_dates"],
    },
    checks: [
      { check: "clip_count", ok: true, message: "5 clips listed / 5 required" },
      { check: "audio_files", ok: false, message: "2 clip(s) need attention" },
    ],
  });
});

afterEach(() => {
  for (const key of Object.keys(process.env)) {
    if (!(key in originalEnv)) delete process.env[key];
  }
  Object.assign(process.env, originalEnv);
});

describe("POST /api/voice-profile/recording-kit/check", () => {
  it("checks a generated recording kit manifest and returns the report", async () => {
    const res = await POST(makeReq({ profileId: "local-default", manifest: "/tmp/anyvoice-kit/manifest.json" }));
    expect(res.status).toBe(200);
    expect(res.headers.get("set-cookie")).toContain(`${ANYVOICE_USER_COOKIE}=`);
    expect(checkKitMock).toHaveBeenCalledWith("/tmp/anyvoice-kit/manifest.json", "local-default");
    const body = await res.json();
    expect(body.check).toMatchObject({
      status: "incomplete",
      summary: { audioFilesPresent: 3 },
    });
  });

  it("uses a default profile id when no JSON body is sent", async () => {
    await POST(makeReq());
    expect(checkKitMock).toHaveBeenCalledWith("", "local-default");
  });

  it("returns an error payload when the check cannot run", async () => {
    checkKitMock.mockRejectedValue(new Error("manifest must be a recording kit manifest generated by AnyVoice"));
    const res = await POST(makeReq({ manifest: "/etc/passwd" }));
    expect(res.status).toBe(500);
    const body = await res.json();
    expect(body).toMatchObject({
      status: "error",
      message: "manifest must be a recording kit manifest generated by AnyVoice",
    });
  });
});
