// @vitest-environment node
import { afterEach, beforeEach, describe, expect, it, vi } from "vitest";

vi.mock("@/lib/recording-kit", () => ({
  normalizeVoiceProfileRecordingKitAudio: vi.fn(),
}));

import { POST } from "@/app/api/voice-profile/recording-kit/normalize/route";
import { normalizeVoiceProfileRecordingKitAudio } from "@/lib/recording-kit";
import { ANYVOICE_USER_COOKIE } from "@/lib/user-session";

const normalizeKitMock = vi.mocked(normalizeVoiceProfileRecordingKitAudio);
const originalEnv = { ...process.env };

function makeReq(body?: unknown): import("next/server").NextRequest {
  return new Request("http://localhost/api/voice-profile/recording-kit/normalize", {
    method: "POST",
    headers: body === undefined ? undefined : { "content-type": "application/json" },
    body: body === undefined ? undefined : JSON.stringify(body),
  }) as unknown as import("next/server").NextRequest;
}

beforeEach(() => {
  vi.clearAllMocks();
  normalizeKitMock.mockResolvedValue({
    status: "normalized",
    manifest: "/tmp/anyvoice-kit/manifest.json",
    profileId: "local-default",
    dryRun: false,
    overwrite: false,
    sourceDirs: ["/tmp/anyvoice-kit/recordings"],
    summary: {
      clips: 5,
      normalized: 5,
      existing: 0,
      missingSources: 0,
      failures: 0,
    },
    rows: [
      {
        id: "profile-clip-01",
        status: "normalized",
        method: "convert",
        sourceAudioPath: "/tmp/anyvoice-kit/recordings/profile-clip-01.m4a",
        audioPath: "/tmp/anyvoice-kit/recordings/profile-clip-01.wav",
      },
    ],
    checkReport: {
      status: "ready_to_import",
      manifest: "/tmp/anyvoice-kit/manifest.json",
      profileId: "local-default",
      summary: {
        clips: 5,
        minClips: 5,
        audioFilesPresent: 5,
        coveredFeatures: ["zh_hant"],
        missingCoverageFeatures: [],
      },
      checks: [{ check: "audio_files", ok: true, message: "all listed recordings exist" }],
    },
  });
});

afterEach(() => {
  for (const key of Object.keys(process.env)) {
    if (!(key in originalEnv)) delete process.env[key];
  }
  Object.assign(process.env, originalEnv);
});

describe("POST /api/voice-profile/recording-kit/normalize", () => {
  it("normalizes external recording files and returns the check report", async () => {
    const res = await POST(makeReq({ profileId: "local-default", manifest: "/tmp/anyvoice-kit/manifest.json" }));
    expect(res.status).toBe(200);
    expect(res.headers.get("set-cookie")).toContain(`${ANYVOICE_USER_COOKIE}=`);
    expect(normalizeKitMock).toHaveBeenCalledWith("/tmp/anyvoice-kit/manifest.json", "local-default");
    const body = await res.json();
    expect(body.normalization).toMatchObject({
      status: "normalized",
      summary: { normalized: 5, missingSources: 0 },
      checkReport: { status: "ready_to_import" },
    });
  });

  it("uses a default profile id when no JSON body is sent", async () => {
    await POST(makeReq());
    expect(normalizeKitMock).toHaveBeenCalledWith("", "local-default");
  });

  it("returns an error payload when normalization cannot run", async () => {
    normalizeKitMock.mockRejectedValue(new Error("manifest must be a recording kit manifest generated by AnyVoice"));
    const res = await POST(makeReq({ manifest: "/etc/passwd" }));
    expect(res.status).toBe(500);
    const body = await res.json();
    expect(body).toMatchObject({
      status: "error",
      message: "manifest must be a recording kit manifest generated by AnyVoice",
    });
  });
});
