// @vitest-environment node
import os from "node:os";
import path from "node:path";
import { mkdir, mkdtemp, rm, writeFile } from "node:fs/promises";
import { afterEach, beforeEach, describe, expect, it } from "vitest";
import {
  checkVoiceProfileRecordingKit,
  getCurrentVoiceProfileRecordingKit,
  normalizeVoiceProfileRecordingKitAudio,
  preflightVoiceProfileRecordingKit,
  readCurrentVoiceProfileRecordingKitCueSheet,
  smokeTestVoiceProfileRecordingKit,
} from "@/lib/recording-kit";

const transcripts = [
  "你好，我正在錄製一段聲音樣本。春天的陽光灑在湖面上，遠方傳來陣陣鳥鳴，世界顯得格外安靜。",
  "日期範例是二零二六年五月二十日，我會用自然的速度，把每一句話清楚地讀完。",
  "如果遇到重要名字，例如 Brenda、AnyVoice、台北、紐約、重慶、銀行、角色、音樂和長樂，我會保持穩定的音量與節奏。",
  "這段錄音包含高低起伏、停頓和短句，目的是讓數位聲音更接近我平常說話的方式。",
  "請確認錄音環境安靜、沒有回音，也不要離麥克風太近，讓聲音保持乾淨自然。",
];

const originalEnv = { ...process.env };
let tmpRoot: string;

function shellQuote(value: string): string {
  return `'${value.replaceAll("'", "'\\''")}'`;
}

beforeEach(async () => {
  tmpRoot = await mkdtemp(path.join(os.tmpdir(), "anyvoice-recording-kit-lib-"));
  process.env.ANYVOICE_RECORDING_KIT_OUT_ROOT = tmpRoot;
  process.env.ANYVOICE_RECORDER_COMMAND = "recorder --out {audio_path} --seconds {duration}";
});

afterEach(async () => {
  await rm(tmpRoot, { recursive: true, force: true });
  for (const key of Object.keys(process.env)) {
    if (!(key in originalEnv)) delete process.env[key];
  }
  Object.assign(process.env, originalEnv);
});

describe("checkVoiceProfileRecordingKit", () => {
  it("returns an incomplete report instead of throwing when generated kit files are missing", async () => {
    const kitDir = path.join(tmpRoot, "local-default-test");
    await mkdir(path.join(kitDir, "recordings"), { recursive: true });
    const clips = transcripts.map((transcript, index) => {
      const stem = `profile-clip-${String(index + 1).padStart(2, "0")}`;
      return {
        id: stem,
        audioPath: `recordings/${stem}.wav`,
        transcript,
      };
    });
    const manifest = path.join(kitDir, "manifest.json");
    await writeFile(manifest, `${JSON.stringify({ clips }, null, 2)}\n`, "utf-8");

    const report = await checkVoiceProfileRecordingKit(manifest, "local-default");
    expect(report.status).toBe("incomplete");
    expect(report.summary).toMatchObject({ clips: 5, audioFilesPresent: 0 });
    expect(report.checks.find((check) => check.check === "coverage")).toMatchObject({ ok: true });
    expect(report.checks.find((check) => check.check === "audio_files")).toMatchObject({ ok: false });
  });

  it("rejects manifest paths outside the generated recording kit root", async () => {
    await expect(checkVoiceProfileRecordingKit("/etc/passwd", "local-default")).rejects.toThrow(
      "manifest must be a recording kit manifest generated by AnyVoice",
    );
  });

  it("loads the current recording kit without creating a new timestamped kit", async () => {
    const kitDir = path.join(tmpRoot, "local-default-current");
    await mkdir(path.join(kitDir, "recordings"), { recursive: true });
    const clips = transcripts.map((transcript, index) => {
      const stem = `profile-clip-${String(index + 1).padStart(2, "0")}`;
      return {
        id: stem,
        audioPath: `recordings/${stem}.wav`,
        transcript,
        recommendedDurationSec: 9 + index,
        durationMode: "auto",
        durationTargetSec: 9 + index,
        coverageFeatures: ["zh_hant", "numbers_dates", "latin_terms", "polyphones", "punctuation_rhythm"],
        sourceKind: "scripted",
      };
    });
    await writeFile(path.join(kitDir, "manifest.json"), `${JSON.stringify({ promptSet: "extended", clips }, null, 2)}\n`, "utf-8");

    const kit = await getCurrentVoiceProfileRecordingKit("local-default");
    expect(kit).toMatchObject({
      status: "written",
      promptSet: "extended",
      manifest: path.join(kitDir, "manifest.json"),
      recordings: path.join(kitDir, "recordings"),
      clips: 5,
      summary: {
        missingCoverageFeatures: [],
        missingPronunciationPresetIds: ["polyphone:bank-president", "brand:voxcpm2"],
      },
    });
    expect(kit?.clipSpecs).toHaveLength(5);
    expect(kit?.cueSheetUrl).toBe(
      `/api/voice-profile/recording-kit/cue-sheet?profileId=local-default&manifest=${encodeURIComponent(path.join(kitDir, "manifest.json"))}`,
    );
    expect(kit?.clipSpecs?.[0]).toMatchObject({
      id: "profile-clip-01",
      expectedStem: "profile-clip-01",
      transcript: transcripts[0],
      recommendedDurationSec: 9,
      durationMode: "auto",
      durationTargetSec: 9,
      pronunciationPresetIds: [],
    });
    expect(kit?.recordMissingUntilCompleteCommand).toContain("--record-missing-until-complete");
    expect(kit?.recordMissingUntilCompleteCommand).toContain("--microphone-smoke-sec 2");
    expect(kit?.recordMissingUntilCompleteCommand).toContain("--auto-duration");
    expect(kit?.recordNextMissingCommand).toContain("--microphone-smoke-sec 2");
    expect(kit?.recordNextMissingCommand).toContain("--auto-duration");
    expect(kit?.recordAllCommand).toContain("--microphone-smoke-sec 2");
    expect(kit?.recordAllCommand).toContain("--auto-duration");
    expect(kit?.preflightBriefCommand).toContain("--auto-duration");
    expect(kit?.normalizeExternalRecordingsCommand).toContain("normalize_voice_profile_recording_kit_audio.py");
  });

  it("reads the current kit cue sheet only from the generated kit root", async () => {
    const kitDir = path.join(tmpRoot, "local-default-current");
    await mkdir(path.join(kitDir, "recordings"), { recursive: true });
    const clips = transcripts.map((transcript, index) => {
      const stem = `profile-clip-${String(index + 1).padStart(2, "0")}`;
      return {
        id: stem,
        audioPath: `recordings/${stem}.wav`,
        transcript,
        sourceKind: "scripted",
      };
    });
    const cueSheetHtml = "<!doctype html><title>AnyVoice cue sheet</title><main>profile-clip-01</main>";
    await writeFile(path.join(kitDir, "manifest.json"), `${JSON.stringify({ promptSet: "extended", clips }, null, 2)}\n`, "utf-8");
    await writeFile(path.join(kitDir, "cue-sheet.html"), cueSheetHtml, "utf-8");

    const cueSheet = await readCurrentVoiceProfileRecordingKitCueSheet("local-default");
    expect(cueSheet).toMatchObject({
      html: cueSheetHtml,
      path: path.join(kitDir, "cue-sheet.html"),
    });
  });

  it("returns a blocked normalization report when phone files have not been copied into the kit", async () => {
    const kitDir = path.join(tmpRoot, "local-default-test");
    await mkdir(path.join(kitDir, "recordings"), { recursive: true });
    const clips = transcripts.map((transcript, index) => {
      const stem = `profile-clip-${String(index + 1).padStart(2, "0")}`;
      return {
        id: stem,
        audioPath: `recordings/${stem}.wav`,
        transcript,
        sourceKind: "scripted",
      };
    });
    const manifest = path.join(kitDir, "manifest.json");
    await writeFile(manifest, `${JSON.stringify({ clips }, null, 2)}\n`, "utf-8");

    const report = await normalizeVoiceProfileRecordingKitAudio(manifest, "local-default");
    expect(report).toMatchObject({
      status: "blocked",
      summary: { clips: 5, normalized: 0, missingSources: 5 },
    });
  });

  it("runs the no-microphone recording preflight for a generated kit", async () => {
    const kitDir = path.join(tmpRoot, "local-default-test");
    await mkdir(path.join(kitDir, "recordings"), { recursive: true });
    const clips = transcripts.map((transcript, index) => {
      const stem = `profile-clip-${String(index + 1).padStart(2, "0")}`;
      return {
        id: stem,
        audioPath: `recordings/${stem}.wav`,
        transcript,
        sourceKind: "scripted",
      };
    });
    const manifest = path.join(kitDir, "manifest.json");
    await writeFile(manifest, `${JSON.stringify({ clips }, null, 2)}\n`, "utf-8");

    const report = await preflightVoiceProfileRecordingKit(manifest, "local-default");
    expect(report).toMatchObject({
      status: "ready_to_record",
      summary: { clips: 5, toRecord: 5, transcriptBlocked: 0, writeBlocked: 0 },
      recorder: { configured: true },
      recordingGuidance: {
        durationMode: "auto",
        targetDurationSec: null,
        targetDurationLabel: "auto per clip",
      },
    });
    const firstClip = report.clips?.[0] as { recommendedDurationSec?: number } | undefined;
    expect(report.clips?.[0]).toMatchObject({
      action: "record",
      durationMode: "auto",
      durationTargetSec: firstClip?.recommendedDurationSec,
      commandPreview: expect.stringContaining("recorder --out"),
    });
  });

  it("runs the opt-in microphone smoke-test preflight without writing kit recordings", async () => {
    const kitDir = path.join(tmpRoot, "local-default-test");
    await mkdir(path.join(kitDir, "recordings"), { recursive: true });
    const clips = transcripts.map((transcript, index) => {
      const stem = `profile-clip-${String(index + 1).padStart(2, "0")}`;
      return {
        id: stem,
        audioPath: `recordings/${stem}.wav`,
        transcript,
        sourceKind: "scripted",
      };
    });
    const manifest = path.join(kitDir, "manifest.json");
    const fakeRecorder = path.join(tmpRoot, "fake_recorder.py");
    await writeFile(manifest, `${JSON.stringify({ clips }, null, 2)}\n`, "utf-8");
    await writeFile(
      fakeRecorder,
      [
        "from pathlib import Path",
        "import sys",
        "import wave",
        "audio_path = Path(sys.argv[1])",
        "duration = float(sys.argv[2])",
        "sample_rate = 8000",
        "frames = max(1, round(duration * sample_rate))",
        "audio_path.parent.mkdir(parents=True, exist_ok=True)",
        "with wave.open(str(audio_path), 'wb') as handle:",
        "    handle.setnchannels(1)",
        "    handle.setsampwidth(2)",
        "    handle.setframerate(sample_rate)",
        "    handle.writeframes(b'\\x00\\x20' * frames)",
        "",
      ].join("\n"),
      "utf-8",
    );
    process.env.ANYVOICE_RECORDER_COMMAND = `${shellQuote(process.env.PYTHON || "python3")} ${shellQuote(fakeRecorder)} {audio_path} {duration}`;

    const report = await smokeTestVoiceProfileRecordingKit(manifest, "local-default", 1);
    expect(report.status).toBe("ready_to_record");
    expect(report.recordingGuidance).toMatchObject({
      durationMode: "auto",
      targetDurationLabel: "auto per clip",
    });
    expect(report.microphoneSmokeTest).toMatchObject({
      status: "passed",
      durationSec: 1,
      clipId: "profile-clip-01",
      keptAudio: false,
    });
    expect(report.microphoneSmokeTest?.audioBytes).toBeGreaterThan(0);
  });
});
